// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SuperHeroAPI.Models;

public partial class Character
{
   // [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Firstname { get; set; }

    public string? Lastname { get; set; }

    public string? Place { get; set; }

    public DateOnly? Birthdate { get; set; }
}