// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SuperHeroAPI.Models;

public partial class Character
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Firstname { get; set; }

    public string? Lastname { get; set; }

    public string? Place { get; set; }

    public DateTime? Birthdate { get; set; }
}